// Generated by Selenium IDE
package com.achieveit.systemtest;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class LoginBasicTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
//    WebDriver driver = new FirefoxDriver();   //Firefox浏览器
//    WebDriver driver = new EdgeDriver();      //Edge浏览器
//    WebDriver driver = new InternetExplorerDriver();  // Internet Explorer浏览器
//    WebDriver driver = new OperaDriver();     //Opera浏览器
//    WebDriver driver = new PhantomJSDriver();   //PhantomJS
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginbasictest() {
    driver.get("http://localhost:8081/login");
    driver.manage().window().setSize(new Dimension(1127, 793));
    driver.findElement(By.cssSelector(".login")).click();
    driver.findElement(By.cssSelector(".login")).click();
    driver.findElement(By.cssSelector(".loginConfirm-text")).click();
  }
}
